### ISSUE TITLE
Organisms that are disconnected

### ISSUE THREAD

**Issue by johnbutlergames** [MaxRobinsonTheGreat/LifeEngine#103]
Maybe this is intentional, but I don't think that organisms are supposed to be disconnected.
It also makes it very confusing because it looks like two organisms when it is really one.

In the organism editor, you have the ability to create organisms that have disconnected cells. Also, sometimes organisms mutate and become disconnected.

To reproduce the bug, go to the editing menu and add a cell that is not adjacent to the initial mouth cell. Then spawn in the organism and it moves around as normal.

I expected it to give an error message saying you cannot make a disconnected organism, and I also expected it not to mutate into disconnected organisms.

Environment: Desktop

**Comment by MaxRobinsonTheGreat** [comment]
I don't consider this a bug, I think it opens interesting possibilities for organisms.
