### ISSUE TITLE
Global mutation rate not restored from world save

### ISSUE THREAD

**Issue by kimbar** [MaxRobinsonTheGreat/LifeEngine#137]
[comment]: <> (ISSUES ARE NOT FOR IDEAS OR SUGGESTIONS)

**Describe the bug**
After saving a world with "Use evolved mutation rate = off" the value of "Global mutation rate" is not restored from the save file even when "Override Evolution Controls = on".  

**To Reproduce**
1. Set "Use evolved mutation rate = off"
2. Set "Global mutation rate = 10"
3. Save "world.json"
4. Set "Global mutation rate = 2"
5. Ensure "Override Evolution Controls = on"
6. Load the "world.json"
7. The value "Global mutation rate = 2"

**Expected behavior**
The value "Global mutation rate = 10"

**Environment:**
 - Desktop
 - Windows 10 64 bit
 - Browsers:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44

**Additional context**
All other  evolution settings seem to be restored properly from world file.

**Comment by MaxRobinsonTheGreat** [comment]
Looks like this was a display issue, and should now be fixed
