### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [MaxRobinsonTheGreat/LifeEngine#20]
Add hotkeys for button controls.

Discussed in https://github.com/MaxRobinsonTheGreat/EvolutionSimulatorV2/discussions/17. Originally posted by **Ketok4321**

**Comment by syspic** [comment]
Awesome! This is actually why I came to this issues page in the first place! I have two suggestions for hotkeys:

p or space - pause
r - restart

**Comment by xkortex** [comment]
>  r - restart

Eh, that might be too easy to nuke your progress. How often are you restarting that you need it as a hotkey? 

> doesnt quite count as a hotkey, but middle mouse button + drag to pan?

+1

**Comment by MaxRobinsonTheGreat** [comment]
Oh should have updated this, hotkeys have been implemented on develop #47. Will close once pushed into master.
