### ISSUE TITLE
Easier way to remove starter organism

### ISSUE THREAD

**Issue by SnivyLlama** [MaxRobinsonTheGreat/LifeEngine#30]
I have to kill it and then use the food icon to clean up the food. Either
1) Have an option to not include the starting organism after resetting
2) Have the kill option not turn it into food or have an option for that

**Comment by MaxRobinsonTheGreat** [comment]
Agreed, I think adding a clear button that removes the org/food would be best.

**Comment by MaxRobinsonTheGreat** [comment]
@SnivyLlama By the way, in the future please make a discussion for feature requests, not an issue. Helps keep things organized.

**Comment by SnivyLlama** [comment]
> @SnivyLlama By the way, in the future please make a discussion for feature requests, not an issue. Helps keep things organized.

Oh, whoops. You can close this now if you want to and I will make a discussion

**Comment by MaxRobinsonTheGreat** [comment]
Nope I would have made an issue for it anyway, I intend to implement it.

**Comment by MaxRobinsonTheGreat** [comment]
implemented with #64
