### ISSUE TITLE
Static food source?

### ISSUE THREAD

**Issue by SelfSealShelf** [MaxRobinsonTheGreat/LifeEngine#52]
There's no way to create a static food source currently.

**Comment by syspic** [comment]
just a note in case you didnt see it: you can create some with your mouse. you can also have some randomly spawn in the world. I understand if your use case isnt one of those though!

**Comment by SelfSealShelf** [comment]
Right now I just used an AHK script to spam clicking. It doesn't work well

I'd like to be able to shape static food sources around walls to evolve certain mouth shapes
