### ISSUE TITLE
Improve reset/close warning

### ISSUE THREAD

**Issue by syspic** [MaxRobinsonTheGreat/LifeEngine#54]
I hope this counts as an issue

When pressing the Reset Environment button, all walls get removed. Sometimes I forget this will happen and will have to redraw everything. 

Why I think this is a bug:
There is a whole button to remove walls (the "Clear all walls" buton) and that asks the user to confirm they are *really* sure they want to delete the walls. This makes it seem important and that we don't want to accidently remove walls. We could use this button to remove the walls even after a reset. Or if the rest button is pressed while walls are drawn, the same alert could be triggered

To reproduce: 
1) draw walls 
2) press "Reset Environment" button (walls also get removed)
3) < intentionally left blank >

Expected option 1: 
1) draw walls 
2) press "Reset Environment" button (walls remain)
3) press "Clear all walls" button to remove walls

Expected option 2: 
1) draw walls 
2) press "Reset Environment" button (walls remain)
3) click ok on alert asking if walls should be removed

**Comment by MaxRobinsonTheGreat** [comment]
I don't think the warning is necessary for clearing walls, and plan on removing it for this button.

I would prefer adding a warning when resetting, resizing, or closing the tab, at least when enough ticks have passed. This makes more sense to me.

**Comment by MaxRobinsonTheGreat** [comment]
#64 implements these improvements. Warnings added to reset, resize, and tab closing.

**Comment by syspic** [comment]
Thank you! That does make sense! 

The only other use case might be if someone wants to keep the walls but reset/restart the simulation. But thats a different use case and maybe not something that is important enough to worry about right now. 

but for instance, it would be cool to have the same walls and run the sim again without clearing anything but all life/food. it would be interesting to see how things evolve differently given the exact same wall structure
